name: coal-blending
channels:
    - conda-forge
dependencies:
- python
- pip
- pip:
  - dj-database-url
  - Django
  - django-heroku
  - oauth2client
  - gspread
  - gunicorn
  - pandas
  - psycopg2
  - whitenoise