name: coal-blending-env
dependencies:
- python
- anaconda
- coinbonmin
- pip:
  - asgiref==3.4.1
  - cachetools==4.2.2
  - certifi==2021.5.30
  - charset-normalizer==2.0.6
  - dj-database-url==0.5.0
  - Django==3.2.7
  - django-heroku==0.3.1
  - google-auth==2.1.0
  - google-auth-oauthlib==0.4.6
  - gspread==4.0.1
  - gunicorn==20.1.0
  - httplib2==0.19.1
  - idna==3.2
  - numpy==1.21.2
  - oauth2client==4.1.3
  - oauthlib==3.1.1
  - pandas==1.3.3
  - psycopg2==2.9.1
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pyparsing==2.4.7
  - python-dateutil==2.8.2
  - python-decouple==3.4
  - pytz==2021.1
  - requests==2.26.0
  - requests-oauthlib==1.3.0
  - rsa==4.7.2
  - six==1.16.0
  - sqlparse==0.4.2
  - urllib3==1.26.7
  - whitenoise==5.3.0